name: wallpaper_app
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.1.0+1
  permission_handler: ^8.3.0
  dio: ^4.0.3
  http: ^0.13.4
  url_launcher: ^6.0.13
  get: ^4.3.8
  flutter_staggered_grid_view: ^0.4.1
  theme_provider: ^0.5.0
  animate_do: ^2.0.0
  font_awesome_flutter: ^9.2.0
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  assets:
    - assets/api_key.txt


  uses-material-design: true
